# ---------- Site basics ----------
locale: "en-US"
title: "Ali A. Isse"
title_separator: "-"
name: "Ali A. Isse"
description: "Personal site"

url: "https://aliaisse.github.io"   # your user domain
baseurl: "/issemehdi"               # MUST match repo name
repository: "aliaisse/issemehdi"

# ---------- Theme (GitHub Pages safe) ----------
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: default
enable_darkmode: false
header_pages: []                    # use _data/navigation.yml for menu

# ---------- Author (sidebar card) ----------
author:
  avatar: "/issemehdi/image/mehdi.jpg"
  name: "Ali A. Isse"
  bio: "PhD Candidate · Nuclear deterrence, coercive diplomacy, preventive war."
  location: "Princeton, NJ"
  employer: "Princeton University"
  email: "ai9431@princeton.edu"

  links:
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/your-id"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/0000-0000-0000-0000"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/aliaisse"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/your-handle/"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/your-handle"

# ---------- Collections ----------
collections:
  publications:
    output: true
    permalink: /publications/:path/
  talks:
    output: true
    permalink: /talks/:path/
  teaching:
    output: true
    permalink: /teaching/:path/

# ---------- Defaults ----------
defaults:
  - scope: { path: "", type: pages }
    values: { layout: single, author_profile: true }
  - scope: { path: "", type: publications }
    values: { layout: single, author_profile: true }
  - scope: { path: "", type: talks }
    values: { layout: single, author_profile: true }
  - scope: { path: "", type: teaching }
    values: { layout: single, author_profile: true }

# ---------- Markdown / Plugins ----------
markdown: kramdown
kramdown: { input: GFM }

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-include-cache

# ---------- Include / Exclude ----------
include:
  - _pages
  - files
exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - package.json*
  - .github
  - README
  - README.md
  - LICENSE

# ---------- Other ----------
permalink: /:categories/:title/
timezone: Etc/UTC
